import type { Metadata } from 'next';
import { ReactQueryProvider } from '@/components/providers/react-query-provider';
import { Toaster } from 'sonner';
import React from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ReactQueryProvider>
          {children}
          <Toaster
            position="top-right"
            duration={5000}
            closeButton
            richColors
          />
        </ReactQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
