FROM node:22.14.0-slim
WORKDIR /apps/backend

# Install pnpm globally
RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

CMD [ "pnpm", "run", "dev" ]